# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c5a2c15cb70bceccaed08f77ed65948be3d85ae4cbb09f9b89a53d02fabd07be993d79fc67cacc9578232006cafb08ff08fed44911a3534c960950d862e5f95

test:
  secret_key_base: e119f427703e735b6f8aa3c145e7b36cd841df410ea35061b31ec84a879b395b18346fb14a3c09a7f10d00f76823cab599bb0afd8c8d1dcfd503bfd399766ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
